# Generated by Django 4.2.1 on 2023-05-27 21:34

from django.db import migrations
import utenti_custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utentecustom',
            managers=[
                ('objects', utenti_custom.models.UserManager()),
            ],
        ),
    ]
