# Generated by Django 4.2.1 on 2023-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti_custom', '0002_alter_utentecustom_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utentecustom',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='immagini_utenti/% Y/% m/% d/'),
        ),
    ]
