# Generated by Django 4.2.1 on 2023-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti_custom', '0004_alter_utentecustom_foto_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utentecustom',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='media/immagini_utenti/%Y/%m/%d/'),
        ),
    ]
