# Generated by Django 4.2.1 on 2023-06-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione_medici', '0003_rename_utente_esame_paziente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
