# Generated by Django 4.2.1 on 2023-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_medici', '0004_alter_medico_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
