# Generated by Django 4.2.1 on 2023-06-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione_medici', '0005_alter_medico_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esame',
            name='paziente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esami', to=settings.AUTH_USER_MODEL),
        ),
    ]
