# Generated by Django 4.2.2 on 2023-06-08 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione_medici', '0006_alter_esame_paziente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(max_length=150)),
                ('data', models.DateField()),
                ('commentatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='gestione_medici.medico')),
            ],
            options={
                'verbose_name_plural': 'Commenti',
                'ordering': ['data'],
            },
        ),
        migrations.AddConstraint(
            model_name='commento',
            constraint=models.UniqueConstraint(fields=('medico', 'commentatore'), name='combinazione_medico_commentatore'),
        ),
    ]
