# Generated by Django 4.2.2 on 2023-06-13 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('in_corso', 'In corso'), ('terminato', 'Terminato')], default='in_attesa', max_length=10)),
                ('indentificativi_utente', models.CharField(max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('membro_assistenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat',
                'ordering': ['data'],
            },
        ),
    ]
