# Generated by Django 4.2.2 on 2023-06-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_assistenza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='indentificativi_utente',
            new_name='identificativi_utente',
        ),
    ]
